#!/bin/bash

# Check TLS headers, in particular what the cipher gets set to.

# Isolate NIC name assocated with the default gateway.
nic="$(route -n | awk '/^0\.0\.0\.0/ {print $8}')";

# Isolate IP address assocated with default gateway.
ip-address="$(ip -4 address show ${nic} | awk '/brd/ && !/\/32/ sub("\\/[[:digit:]]{1,2}","") {print $2}')";

# Generate list of ports in a listening state.
ports-list="$(ss -l4n | awk '{print $5}' | awk -F: '{print $2}' | sort -u)";

# Query each listening port, and extract TLS cipher.
for port in ${ports-list}; do
    printf "Testing port ${port}: "; curl --max-time 2 -s -v https://${ip-address}:${port}/ 2>&1 | grep "connection using"; echo;
done | grep "*";
